baseURL = "https://example.org/"
languageCode = "en-us"
title = "8500 Hugo Demo"
theme = "PaperMod"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3

[[menu.main]]
name = "Research"
url = "/research"
weight = 4

[[menu.main]]
name = "CV"
url = "/cv"
weight = 5

[markup.goldmark.renderer]
unsafe = true
